test: &default

  # Credentials for REST APIs
  client_id: AYzQPdzO8EcEuWD5eG5VhAhL78QQkJYWxkK2mDqeBvilYNDWqmAkb8EsSpJ4JZkZWCHvubZX-TtjAMBr
  client_secret: EPFOssSAG-KxNK52Yfh7is2R7UueB2cPy0zGraqyWY6guFLSO2UdMpKhS2ObsZlbvtGoN0NeKu8mqaW_

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: finance-facilitator_api1.mouselive.com
  password: 4DLMYL3CVAHZFECU
  signature: Agwx2rdN5v3.RPZH5.5Xz5Tg0q4eADBq9lGEzGjVCtNLQyjmtbIlkdK6
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: finance-facilitator@mouselive.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: sandbox
